### ISSUE TITLE
Q1 Goals

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/codefund#1]
#### Homepage content
- [ ] How it works
- [ ] Testimonials
- [ ] Ethical Advertising
- [ ] Contact
- [ ] Live stats (#32)
- [ ] FAQ
- [ ] Newsletter integration (mailchimp)
- [ ] Add better messaging UX (for flash messages)

#### Login
- [x] Email
- [ ] GitHub (#28)
- [ ] GitLab (#30)
- [ ] BitBucket (#29)

#### Register
- [x] Email (#25)
- [ ] GitHub
- [ ] GitLab
- [ ] BitBucket

#### Manage profile
- [ ] View (#24)
- [ ] Edit (#23)
- [ ] Manage payment information
- [ ] Legal agreement
- [ ] Add funds (#22)
 
#### Property management
- [x] Add new website
- [x] Update existing website
- [ ] Code for adding to property location (test / live) (#31)

#### Dashboard
- [x] Impressions (#15)
- [x] Clicks (#14)
- [ ] Earnings (#27)
- [ ] Distribution History (#26)

#### Funding History
- [ ] List (#21)
- [ ] View Receipt (#20)

#### Creative Management
- [x] Create Ad (#19)
- [x] Update Ad (#18)

#### Property search
- [x] List all properties in paginated table (#17)
- [ ] Select projects to sponsor (#16)

#### Administration
- [ ] Ability to accept crypto as form of funding from sponsors (#13)
- [ ] Ability to distribute funds as crypt to developers (#12)
- [x] Integrate Rollbar (#11)

**Comment by WizardOfAus** [comment]
How does Codesponsor work? Very cool idea and keen to find out more!

**Comment by snewcomer** [comment]
Woah nice!  I'd be excited to help out if possible!

Is the registration "Email" just email signup with magic links or email + password?

**Comment by coderberry** [comment]
@snewcomer I'd love to have your help.. the reason it didn't work before is b/c of a small bug.. For now, I am not allowing new signups on the live system, but please feel free to help out with these tasks. I'll be creating tickets around those that need to be done.

**Comment by coderberry** [comment]
@WizardOfAus Code Sponsor provides a small snippet of code that goes in your website. It will show an ethical, relevant ad to those visiting your site. You get paid a percentage on every click.

**Comment by WizardOfAus** [comment]
@coderberry What is an 'ethical' ad and how is this different to existing ad and affiliate networks?

**Comment by coderberry** [comment]
@WizardOfAus this describes ethical advertising well and is the foundation of our advertising methodology
