### ISSUE TITLE
Enable API-based impression tracking

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/codefund#301]
### User Story

As a platform owner, I want to integrate directly with CodeFund via API in order to fetch the ad creative and display it natively.

### Why Is this Needed?

This is a requirement for us to integrate with platforms in the future such as codesandbox.io, cmty.io and more.

### Description

*Type*: Feature

### Definition of Done

- [x] Allow IP address, width, height, user agent to be passed in original request (IP is required)
- [x] Use an API token that can be revoked
- [x] Provide API documentation
- [x] Enable / Disable API access on user (admin only)

Extra credit:
- [x] Allow publisher to refresh their token (generate new)
- [x] Include `house_ad` boolean in the API response
